name: "Test set-output"
#on: [workflow_dispatch, push]
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!release_doc'

jobs:
  build:
    runs-on: ubuntu-20.04 #latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.9', '3.10' ]
    name: Python ${{ matrix.python-version }}
    steps:
      - name: Get branch name via set-output
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo ${GITHUB_REF#refs/heads/}
        id: extract_branch

      - name: Get branch name (new)
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch_new

      - name: display branch 1
        run-name: Get branch via set-output - branch is '${{ steps.extract_branch.outputs.branch }} - event {{ github.event_name }}
        run: echo "branch via set-output - branch is '${{ steps.extract_branch.outputs.branch }}'"

      - name: display branch 2
        run-name: Get branch (new) - branch is '${{ steps.extract_branch.outputs.branch }} - event {{ github.event_name }}
        run: echo "branch (new) - branch is '${{ steps.extract_branch_new.outputs.branch }}'"

      - name: display base branch on PR
        if: github.event_name == 'pull_request'
        run: echo "Base branch - branch is '${{ github.base_ref }}'"

      - name: display base branch if no PR
        if: github.event_name != 'pull_request'
        run: echo "Base branch - branch is '${{ steps.extract_branch_new.outputs.branch }}'"
